piece:
  tonic: C
  scale_type: major
  n_voices: 4
  lowest_note: C4
  highest_note: C6
  sonorities_durations:
    # 1st measure
    - 0.5
    - 0.25
    - 0.25
    # 2nd measure
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    # 3rd measure
    - 0.25
    - 0.125
    - 0.125
    - 0.25
    - 0.125
    - 0.125
    # 4th measure
    - 0.5
    - 0.25
    - 0.125
    - 0.125
    # 5th measure
    - 0.5
    - 0.5
    # 6th measure
    - 0.5
    - 0.25
    - 0.25
    # 7th measure
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    # 8th measure
    - 1.0
rendering:
  dir: geniartor_data
  measure_in_seconds: 1.0
  midi:
    instrument: 0
    velocity: 100
  sinethesizer:
    timbre: default_timbre
    volume: 0.3
optimization:
  population_size: 100
  elite_fraction: 0.1
  smoothing_coef: 0.25
  std: 0.25
  aggregation_fn: mean
  parallelling_params:
    n_processes:
    max_tasks_per_child: 1
evaluation:
  scoring_coefs:
    downbeat_stability: 1
  scoring_fn_params:
    downbeat_stability:
      n_semitones_to_stability:
        0: 1
        1: 0.2
        2: 0.2
        3: 0.7
        4: 0.8
        5: 0.5
        6: 0.0
        7: 0.9
        8: 0.6
        9: 0.6
        10: 0.2
        11: 0.2
