piece:
  tonic: C
  scale_type: major
  lowest_note: C3
  highest_note: C6
  n_measures: 8
  lines_durations:
      - null
      - null
      - null
      - null
  duration_weights:
    0.125: 0.1
    0.25: 0.4
    0.5: 0.4
    1.0: 0.1
  valid_rhythmic_patterns:
    - - 1.0
    - - 0.5
      - 0.5
    - - 0.5
      - 0.25
      - 0.25
    - - 0.5
      - 0.25
      - 0.125
      - 0.125
    - - 0.25
      - 0.25
      - 0.25
      - 0.25
    - - 0.25
      - 0.25
      - 0.25
      - 0.125
      - 0.125
    - - 0.25
      - 0.125
      - 0.125
      - 0.25
      - 0.25
    - - 0.5
      - 1.0
    - - 0.25
      - 0.25
      - 1.0
    - - 0.25
      - 0.125
      - 0.125
      - 1.0

rendering:
  dir: geniartor_data
  common:
    measure_in_seconds: 2.0
    opening_silence_in_seconds: 1.0
    trailing_silence_in_seconds: 1.0
  midi:
    instrument: 0
    velocity: 100
  sinethesizer:
    timbre: default_timbre
    volume: 0.25

optimization:
  n_passes: 5
  perturbation_probability: 0.3

evaluation:
  scoring_coefs:
    absence_of_large_intervals: 1
    absence_of_narrow_ranges: 1
    absence_of_voice_crossing: 1
    conjunct_motion: 1
    harmonic_stability: 1
    tonal_stability: 1
  scoring_fn_params:
    absence_of_large_intervals:
      max_n_semitones: 16
    absence_of_narrow_ranges:
      min_size: 9
      penalties:
        2: 1
        3: 0.5
    conjunct_motion:
      penalty_deduction_per_line: 1.0
      n_semitones_to_penalty:
        0: 0.2
        1: 0.0
        2: 0.0
        3: 0.1
        4: 0.2
        5: 0.3
        6: 0.4
        7: 0.5
        8: 0.6
        9: 0.7
        10: 0.8
        11: 0.9
        12: 1.0
    harmonic_stability:
      min_stabilities:
        beginning: 0.8
        ending: 0.9
        downbeat: 0.75
        middle: 0.5
        other: 0.25
      n_semitones_to_stability:
        0: 1.0
        1: 0.2
        2: 0.2
        3: 0.7
        4: 0.8
        5: 0.5
        6: 0.0
        7: 0.9
        8: 0.6
        9: 0.6
        10: 0.2
        11: 0.2
    tonal_stability:
      min_stabilities:
        beginning: 0.7
        ending: 0.9
        downbeat: 0.7
        middle: 0.5
        other: 0.2
      degree_to_stability:
        1: 1.0
        2: 0.4
        3: 0.7
        4: 0.4
        5: 0.8
        6: 0.4
        7: 0.0
